# Generated by Django 2.0.13 on 2019-08-05 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevconMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='User uuid')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='Phone')),
                ('company', models.CharField(max_length=256, null=True, verbose_name='Company')),
                ('designation', models.CharField(max_length=256, null=True, verbose_name='Designation')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]