# Generated by Django 2.0.13 on 2019-08-24 06:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='User uuid')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='Phone')),
                ('company', models.CharField(max_length=256, null=True, verbose_name='Company')),
                ('designation', models.CharField(max_length=256, null=True, verbose_name='Designation')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('topic', models.CharField(max_length=256, null=True, verbose_name='Topic')),
                ('topic_desc', models.CharField(max_length=512, null=True, verbose_name='Topic description')),
            ],
        ),
        migrations.AlterField(
            model_name='devconmember',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
