# Generated by Django 2.0.13 on 2019-11-01 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190824_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='User uuid')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
