# Generated by Django 2.0.13 on 2019-11-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_prospectus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prospectus',
            new_name='Prospect',
        ),
    ]
